Traceback (most recent call last):
  File "main.py", line 136, in <lambda>
  File "main.py", line 140, in move_on
  File "main.py", line 149, in __init__
  File "main.py", line 69, in get_cursor
sqlite3.OperationalError: unable to open database file
