Traceback (most recent call last):
  File "main.py", line 535, in <module>
  File "main.py", line 120, in __init__
  File "main.py", line 127, in setup_UI
  File "main.py", line 97, in wrapper
FileNotFoundError: [Errno 2] No such file or directory: 'data_files/log.txt'
Traceback (most recent call last):
  File "main.py", line 535, in <module>
  File "main.py", line 120, in __init__
  File "main.py", line 127, in setup_UI
  File "main.py", line 97, in wrapper
FileNotFoundError: [Errno 2] No such file or directory: 'data_files/log.txt'
